// Auto-generated by zimic@0.8.0-canary.0
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpSchema } from '@/http';

export type MyServiceSchema = HttpSchema.Paths<{}>;
