// Auto-generated by zimic@0.8.0-canary.0.

import type { HttpFormData, HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema.Paths<{
  '/upload-with-literal-form-data': {
    POST: {
      request: {
        body: HttpFormData<{
          /** The name of the file */
          name: string;
          /**
           * Format: binary
           *
           * The content of the file
           */
          content: Blob | null;
        }>;
      };
      response: {
        /** Success */
        200: {
          body: HttpFormData<{
            /** The name of the file */
            name?: string;
            /**
             * Format: binary
             *
             * The content of the file
             */
            content: Blob | null;
          }>;
        };
      };
    };
  };
  '/upload-with-component-form-data': {
    POST: {
      request: MyServiceComponents['requests']['formDataUpload'];
      response: {
        200: MyServiceComponents['responses']['Success'];
      };
    };
  };
}>;

export interface MyServiceComponents {
  responses: {
    /** Success */
    Success: HttpSchema.Response<{
      body: HttpFormData<{
        /** The name of the file */
        name?: string;
        /**
         * Format: binary
         *
         * The content of the file
         */
        content: Blob | null;
      }>;
    }>;
  };
  requests: {
    formDataUpload: HttpSchema.Request<{
      body: HttpFormData<{
        /** The name of the file */
        name: string;
        /**
         * Format: binary
         *
         * The content of the file
         */
        content: Blob | null;
      }>;
    }>;
  };
}
