// Auto-generated by zimic@0.7.1.

import type { HttpFormData, HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema.Paths<{
  '/upload-with-literal-form-data': {
    POST: {
      request: {
        body: HttpFormData<{
          name: string;
          content: Blob | null;
        }>;
      };
      response: {
        200: {
          body: HttpFormData<{
            name?: string;
            content: Blob | null;
          }>;
        };
      };
    };
  };
  '/upload-with-component-form-data': {
    POST: {
      request: MyServiceComponents['requests']['formDataUpload'];
      response: {
        200: MyServiceComponents['responses']['Success'];
      };
    };
  };
}>;

export interface MyServiceComponents {
  responses: {
    Success: HttpSchema.Response<{
      body: HttpFormData<{
        name?: string;
        content: Blob | null;
      }>;
    }>;
  };
  requests: {
    formDataUpload: HttpSchema.Request<{
      body: HttpFormData<{
        name: string;
        content: Blob | null;
      }>;
    }>;
  };
}
