// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpFormData, HttpFormDataSerialized, HttpSchema } from '@/http';

export type MyServiceSchema = HttpSchema.Paths<{
  '/upload-with-literal-form-data': {
    POST: {
      request: {
        body: HttpFormData<
          HttpFormDataSerialized<{
            /** The name of the file */
            name: string;
            /**
             * Format: binary
             *
             * The content of the file
             */
            content: Blob | null;
          }>
        >;
      };
      response: {
        /** Success */
        200: {
          body: HttpFormData<
            HttpFormDataSerialized<{
              /** The name of the file */
              name?: string;
              /**
               * Format: binary
               *
               * The content of the file
               */
              content: Blob | null;
            }>
          >;
        };
      };
    };
  };
  '/upload-with-component-form-data': {
    POST: {
      request: MyServiceComponents['requests']['formDataUpload'];
      response: {
        200: MyServiceComponents['responses']['Success'];
      };
    };
  };
}>;

export interface MyServiceComponents {
  responses: {
    /** Success */
    Success: HttpSchema.Response<{
      body: HttpFormData<
        HttpFormDataSerialized<{
          /** The name of the file */
          name?: string;
          /**
           * Format: binary
           *
           * The content of the file
           */
          content: Blob | null;
        }>
      >;
    }>;
  };
  requests: {
    formDataUpload: HttpSchema.Request<{
      body: HttpFormData<
        HttpFormDataSerialized<{
          /** The name of the file */
          name: string;
          /**
           * Format: binary
           *
           * The content of the file
           */
          content: Blob | null;
        }>
      >;
    }>;
  };
}
