// Auto-generated by zimic@0.8.0-canary.0
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpHeadersSerialized, HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema.Paths<{
  '/users-with-non-numeric-status-codes': {
    POST: {
      response: {
        '2xx': MyServiceComponents['responses']['userCreated'];
        '4XX': MyServiceComponents['responses']['error'];
        default: MyServiceComponents['responses']['error'];
      };
    };
  };
  '/users-with-no-request': {
    POST: {
      response: {
        200: MyServiceComponents['responses']['userCreated'];
        400: MyServiceComponents['responses']['error'];
      };
    };
  };
  '/users-with-multiple-reference-response-contents': {
    POST: {
      response: {
        200: MyServiceComponents['responses']['userCreatedMultipleContents'];
        400: MyServiceComponents['responses']['error'];
      };
    };
  };
  '/users-with-multiple-literal-response-contents': {
    POST: {
      response: {
        200:
          | {
              headers: HttpHeadersSerialized<{
                'content-type': 'application/json';
              }>;
              body: {
                type: 'user-as-json';
                value: MyServiceComponents['schemas']['User'];
              };
            }
          | {
              headers: HttpHeadersSerialized<{
                'content-type': 'application/xml';
              }>;
              body: {
                type: 'user-as-xml';
                value: MyServiceComponents['schemas']['User'];
              };
            };
        400: MyServiceComponents['responses']['error'];
      };
    };
  };
  '/users-with-multiple-literal-response-contents-having-headers': {
    POST: {
      response: {
        200:
          | {
              headers: HttpHeadersSerialized<{
                'content-type': 'application/json';
                'x-value'?: string;
              }>;
              body: {
                type: 'user-as-json';
                value: MyServiceComponents['schemas']['User'];
              };
            }
          | {
              headers: HttpHeadersSerialized<{
                'content-type': 'application/xml';
                'x-value'?: string;
              }>;
              body: {
                type: 'user-as-xml';
                value: MyServiceComponents['schemas']['User'];
              };
            };
        400: MyServiceComponents['responses']['error'];
      };
    };
  };
  '/users-with-no-response-content': {
    POST: {
      response: {
        200: {};
      };
    };
  };
  '/users-with-no-request-or-response': {
    POST: {};
  };
}>;

export interface MyServiceComponents {
  schemas: {
    User: {
      id: string;
      name?: string;
      email: string;
      createdAt: string;
      updatedAt: string;
    };
  };
  responses: {
    userCreated: HttpSchema.Response<{
      body: MyServiceComponents['schemas']['User'];
    }>;
    userCreatedMultipleContents: HttpSchema.Response<
      | {
          headers: HttpHeadersSerialized<{
            'content-type': 'application/json';
          }>;
          body: {
            type?: 'user-as-json';
            value?: MyServiceComponents['schemas']['User'];
          };
        }
      | {
          headers: HttpHeadersSerialized<{
            'content-type': 'application/xml';
          }>;
          body: {
            type?: 'user-as-xml';
            value?: MyServiceComponents['schemas']['User'];
          };
        }
    >;
    error: HttpSchema.Response<{
      body: {
        message: string;
      };
    }>;
  };
}
