// Auto-generated by zimic@0.7.1.
// Note! Changes to this file will be overwritten.

import type { HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema.Paths<{
  '/users-with-multiple-security-schemes': {
    POST: {
      response: {
        200: {};
      };
    };
  };
  '/users-with-bearer-auth': {
    POST: {
      response: {
        200: {};
      };
    };
  };
  '/users-with-api-key': {
    POST: {
      response: {
        200: {};
      };
    };
  };
  '/users-with-bearer-oauth2': {
    POST: {
      response: {
        200: {};
      };
    };
  };
}>;
