// Auto-generated by zimic@0.8.0-canary.0.

import type { HttpHeadersSerialized, HttpSchema, HttpSearchParamsSerialized } from '@/index';

export type MyServiceSchema = HttpSchema.Paths<{
  '/users': {
    /** List users */
    GET: MyServiceOperations['users/list'];
    /** Create user */
    POST: MyServiceOperations['users/create'];
  };
}>;

export interface MyServiceComponents {
  schemas: {
    User: {
      /**
       * The user's id
       *
       * @example
       *   be8253f9-124b-4c32-b046-c25b6fd0af0c
       */
      id: string;
      /**
       * The user's name
       *
       * @example
       *   John;
       */
      name?: string;
      /**
       * The user's email
       *
       * @example
       *   john@email.com
       */
      email: string;
      /**
       * The user's creation date
       *
       * @example
       *   2024-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * The user's last update date
       *
       * @example
       *   2024-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
  };
}

export interface MyServiceOperations {
  'users/list': HttpSchema.Method<{
    request: {
      searchParams: HttpSearchParamsSerialized<{
        /** How many items to return */
        limit: number;
        /** The UTM source */
        utm_source?: string;
      }>;
      headers: HttpHeadersSerialized<{
        /** The authorization token */
        authorization: string;
      }>;
    };
    response: {
      /** Success */
      200: {
        body: MyServiceComponents['schemas']['User'][];
      };
      /** Error */
      400: {
        body: {
          message: string;
        };
      };
    };
  }>;
  'users/create': HttpSchema.Method<{
    /** The user to create */
    request: {
      searchParams: HttpSearchParamsSerialized<{
        /** The UTM source */
        utm_source?: string;
      }>;
      headers: HttpHeadersSerialized<{
        /** The authorization token */
        authorization: string;
      }>;
      body: {
        /**
         * The user's name
         *
         * @example
         *   John;
         */
        name?: string;
        /**
         * The user's email
         *
         * @example
         *   john@email.com
         */
        email: string;
        /**
         * The user's password
         *
         * @example
         *   123456;
         */
        password: string;
      };
    };
    response: {
      /** The user was created successfully */
      200: {
        body: MyServiceComponents['schemas']['User'];
      };
      /** Error */
      400: {
        body: {
          /** The error message */
          message: string;
        };
      };
    };
  }>;
}
