import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  zimic: [
    {
      type: 'autogenerated',
      dirName: 'zimic/1-index',
    },
    {
      type: 'category',
      label: 'Getting started',
      link: {
        type: 'generated-index',
        slug: 'getting-started',
      },
      items: [
        {
          type: 'link',
          href: '/docs/http',
          label: '@zimic/http',
          description: 'Get started with @zimic/http.',
        },
        {
          type: 'link',
          href: '/docs/fetch',
          label: '@zimic/fetch',
          description: 'Get started with @zimic/fetch.',
        },
        {
          type: 'link',
          href: '/docs/interceptor',
          label: '@zimic/interceptor',
          description: 'Get started with @zimic/interceptor.',
        },
      ],
    },
    {
      type: 'autogenerated',
      dirName: 'zimic/2-examples',
    },
    {
      type: 'category',
      label: 'API',
      link: { type: 'generated-index', slug: 'api' },
      collapsed: true,
      items: [
        {
          type: 'link',
          href: '/docs/http/api',
          label: '@zimic/http',
          description: 'API reference for @zimic/http.',
        },
        {
          type: 'link',
          href: '/docs/fetch/api',
          label: '@zimic/fetch',
          description: 'API reference for @zimic/fetch.',
        },
        {
          type: 'link',
          href: '/docs/interceptor/api',
          label: '@zimic/interceptor',
          description: 'API reference for @zimic/interceptor.',
        },
      ],
    },
    {
      type: 'category',
      label: 'CLI',
      link: { type: 'generated-index', slug: 'cli' },
      collapsed: true,
      items: [
        {
          type: 'link',
          href: '/docs/http/cli',
          label: '@zimic/http',
          description: 'CLI reference for @zimic/http.',
        },
        {
          type: 'link',
          href: '/docs/interceptor/cli',
          label: '@zimic/interceptor',
          description: 'CLI reference for @zimic/interceptor.',
        },
      ],
    },
  ],

  http: [
    {
      type: 'category',
      label: '@zimic/http',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'zimic-http' }],
    },
  ],

  fetch: [
    {
      type: 'category',
      label: '@zimic/fetch',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'zimic-fetch' }],
    },
  ],

  interceptor: [
    {
      type: 'category',
      label: '@zimic/interceptor',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'zimic-interceptor' }],
    },
  ],
};

export default sidebars;
