import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  zimic: [
    {
      type: 'autogenerated',
      dirName: 'zimic',
    },
    {
      type: 'category',
      label: 'Get started',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'generated-index',
        slug: 'get-started',
      },
      items: [
        {
          type: 'link',
          href: '/docs/http',
          label: '@zimic/http',
        },
        {
          type: 'link',
          href: '/docs/fetch',
          label: '@zimic/fetch',
        },
        {
          type: 'link',
          href: '/docs/interceptor',
          label: '@zimic/interceptor',
        },
      ],
    },
    {
      type: 'category',
      label: 'API',
      collapsed: false,
      collapsible: true,
      link: {
        type: 'generated-index',
        slug: 'api',
      },
      items: [
        {
          type: 'link',
          href: '/docs/http/api',
          label: '@zimic/http',
        },
        {
          type: 'link',
          href: '/docs/fetch/api',
          label: '@zimic/fetch',
        },
        {
          type: 'link',
          href: '/docs/interceptor/api',
          label: '@zimic/interceptor',
        },
      ],
    },
  ],

  http: [
    {
      type: 'category',
      label: '@zimic/http',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'zimic-http' }],
    },
  ],

  fetch: [
    {
      type: 'category',
      label: '@zimic/fetch',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'zimic-fetch' }],
    },
  ],

  interceptor: [
    {
      type: 'category',
      label: '@zimic/interceptor',
      collapsed: false,
      collapsible: false,
      items: [{ type: 'autogenerated', dirName: 'zimic-interceptor' }],
    },
  ],
};

export default sidebars;
