version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: '00:00'
    labels:
      - dependencies
    commit-message:
      prefix: chore(root)
    target-branch: canary
    groups:
      npm:
        patterns:
          - '*'
    ignore:
      # Blocked by https://github.com/zimicjs/zimic/issues/1366.
      - dependency-name: msw
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/*
    schedule:
      interval: monthly
      time: '00:00'
    labels:
      - dependencies
    commit-message:
      prefix: chore(root)
    target-branch: canary
    groups:
      github-actions:
        patterns:
          - '*'
