packages:
  - apps/*
  - packages/*
  - examples
  - examples/*
  - docs/*
onlyBuiltDependencies:
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@zimic/interceptor'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - sharp
  - unrs-resolver
