minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@zimic/*'
  - '@types/*'

packages:
  - apps/*
  - packages/*
  - examples
  - examples/*
  - docs/*

onlyBuiltDependencies:
  - '@swc/core'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - sharp
  - unrs-resolver

overrides:
  form-data@4: ^4.0.4

  glob@7: ^10.5.0
  glob@8: ^10.5.0
  glob@9: ^10.5.0
  glob@10: ^10.5.0

  lodash@4: ^4.17.23

  node-forge@1: ^1.3.2

  mdast-util-to-hast@13: ^13.2.1
