minimumReleaseAge: 1440

packages:
  - apps/*
  - packages/*
  - examples
  - examples/*
  - docs/*

onlyBuiltDependencies:
  - '@swc/core'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - sharp
  - unrs-resolver

overrides:
  form-data: ^4.0.4
  glob: ^10.5.0
  node-forge: ^1.3.2
