packages:
  - apps/*
  - packages/*
  - examples
  - examples/*
  - docs/*

onlyBuiltDependencies:
  - '@swc/core'
  - bufferutil
  - core-js
  - core-js-pure
  - esbuild
  - msw
  - rollup
  - sharp
  - unrs-resolver
