import clsx from 'clsx';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';

import '../styles/global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Search a GitHub repository',
  description: 'Generated by create-next-app',
};

function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en">
      <body className={clsx(inter.className, 'bg-slate-100 flex flex-col items-center justify-center min-h-screen')}>
        {children}
      </body>
    </html>
  );
}

export default RootLayout;
