import clsx from 'clsx';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';

import '../styles/global.css';
import { loadInterceptors } from '../../tests/interceptors';
import InterceptorProvider from '../providers/InterceptorProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create-next-app',
};

async function RootLayout({ children }: PropsWithChildren) {
  if (process.env.NODE_ENV === 'development') {
    await loadInterceptors();
  }

  return (
    <html lang="en">
      <body className={clsx(inter.className, 'bg-slate-100 flex flex-col items-center justify-center min-h-screen')}>
        <InterceptorProvider>{children}</InterceptorProvider>
      </body>
    </html>
  );
}

export default RootLayout;
