// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpHeadersSerialized, HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema<{
  '/binary-upload': {
    POST: {
      request: {
        headers: HttpHeadersSerialized<{
          'content-type': 'application/octet-stream';
        }>;
        body: Blob;
      };
      response: {
        /** Success */
        200: {
          headers: HttpHeadersSerialized<{
            'content-type': 'application/octet-stream';
          }>;
          body: Blob | null;
        };
      };
    };
  };
}>;
