// Auto-generated by @zimic/http.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema<{
  '/binary-upload': {
    POST: {
      request: {
        headers: {
          'content-type': 'application/octet-stream';
        };
        body: Blob;
      };
      response: {
        /** Success */
        200: {
          headers: {
            'content-type': 'application/octet-stream';
          };
          body: Blob | null;
        };
      };
    };
  };
}>;
