// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema<{
  '/binary-upload': {
    POST: {
      request: {
        body: Blob;
      };
      response: {
        /** Success */
        200: {
          body: Blob | null;
        };
      };
    };
  };
}>;
