// Auto-generated by @zimic/http.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema<{
  users: {
    GET: {
      request: {
        searchParams: {
          search?: string;
        };
      };
      response: {
        200: {
          headers: {
            'content-type': 'application/json';
          };
          body: MyServiceComponents['schemas']['Users'];
        };
      };
    };
  };
  '/users/:userId': {
    GET: {
      response: {
        200: {
          headers: {
            'content-type': 'application/json';
          };
          body: MyServiceComponents['schemas']['User'];
        };
      };
    };
  };
  '/users/:userId/friends/': {
    GET: {
      response: {
        200: {
          headers: {
            'content-type': 'application/json';
          };
          body: MyServiceComponents['schemas']['Users'];
        };
      };
    };
  };
  '/notifications': {
    GET: MyServiceOperations['getNotifications'];
  };
}>;

export interface MyServiceComponents {
  schemas: {
    User: {
      id: number;
      name: string;
    };
    Users: MyServiceComponents['schemas']['User'][];
    Notification: {
      id: number;
      message: string;
    };
    Notifications: MyServiceComponents['schemas']['Notification'][];
  };
  parameters: {
    from: string;
  };
}

export interface MyServiceOperations {
  getNotifications: {
    request: {
      searchParams: {
        from?: MyServiceComponents['parameters']['from'];
      };
    };
    response: {
      200: {
        headers: {
          'content-type': 'application/json';
        };
        body: MyServiceComponents['schemas']['Notifications'];
      };
    };
  };
}
