// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpHeadersSerialized, HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema<{
  '/users/:userId': {
    GET: {
      response: {
        200: {
          headers: HttpHeadersSerialized<{
            'content-type': 'application/json';
          }>;
          body: MyServiceComponents['schemas']['User'];
        };
      };
    };
    PUT: {
      request: {
        headers: HttpHeadersSerialized<{
          'content-type': 'application/json';
        }>;
        body: MyServiceComponents['schemas']['User'];
      };
      response: {
        204: {};
      };
    };
    PATCH: {
      request: {
        headers: HttpHeadersSerialized<{
          'content-type': 'application/json';
        }>;
        body: {
          name?: string;
        };
      };
      response: {
        204: {};
      };
    };
  };
}>;

export interface MyServiceComponents {
  schemas: {
    User: {
      id: number;
      name: string;
    };
  };
}
