// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpFormData, HttpSchema, HttpSearchParams } from '@/index';

export type MyServiceSchema = HttpSchema<{
  users: {
    POST: {
      request: {
        headers: {
          'content-type': 'application/json';
        };
        body: {
          name: string;
        };
      };
      response: {
        200: {
          headers: {
            'content-type': 'application/json';
          };
          body: MyServiceComponents['schemas']['User'];
        };
      };
    };
  };
  '/users/:userId': {
    GET: {
      response: {
        200: {
          headers: {
            'content-type': 'application/json';
          };
          body: MyServiceComponents['schemas']['User'];
        };
      };
    };
    PUT: {
      request: {
        headers: {
          'content-type': 'application/json';
        };
        body: MyServiceComponents['schemas']['User'];
      };
      response: {
        204: {};
      };
    };
  };
  '/users/:userId/friends/': {
    GET: {
      response: {
        200: {
          headers: {
            'content-type': 'application/json';
          };
          body: MyServiceComponents['schemas']['Users'];
        };
      };
    };
  };
  '/notifications': {
    DELETE: MyServiceOperations['deleteNotifications'];
  };
  '/uploads': {
    POST: {
      request: MyServiceComponents['requests']['fileUpload'] & {
        headers: {
          'api-key': string;
        };
      };
      response: {
        200:
          | {
              headers: {
                'content-type': 'application/json';
                'x-upload-id'?: string;
              };
              body: {
                id?: string;
              };
            }
          | {
              headers: {
                'content-type': 'x-www-form-urlencoded';
                'x-upload-id'?: string;
              };
              body: HttpSearchParams<{
                id?: string;
              }>;
            };
      };
    };
  };
}>;

export interface MyServiceComponents {
  schemas: {
    User: {
      id: number;
      name: string;
    };
    Users: MyServiceComponents['schemas']['User'][];
    Notification: {
      id: number;
      message: string;
    };
    Notifications: MyServiceComponents['schemas']['Notification'][];
  };
  responses: {
    error: {
      headers: {
        'content-type': 'application/json';
      };
      body: {
        message: string;
      };
    };
  };
  parameters: {
    from: string;
    authorization: string;
  };
  requests: {
    fileUpload: {
      headers: {
        'content-type': 'multipart/form-data';
      };
      body: HttpFormData<{
        name: string;
        content: Blob | null;
      }>;
    };
  };
}

export interface MyServiceOperations {
  getNotifications: {
    request: {
      searchParams: {
        from?: MyServiceComponents['parameters']['from'];
      };
    };
    response: {
      200: {
        headers: {
          'content-type': 'application/json';
        };
        body: MyServiceComponents['schemas']['Notifications'];
      };
    };
  };
  deleteNotifications: {
    request: {
      headers: {
        authorization: MyServiceComponents['parameters']['authorization'];
      };
    };
    response: {
      204: {};
      400: MyServiceComponents['responses']['error'];
    };
  };
}
