// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema<{
  '/users/:userId': {
    GET: {
      response: {
        200: {
          headers: {
            'content-type': 'application/json';
          };
          body: MyServiceComponents['schemas']['User'];
        };
      };
    };
    PUT: {
      request: {
        headers: {
          'content-type': 'application/json';
        };
        body: MyServiceComponents['schemas']['User'];
      };
      response: {
        204: {};
      };
    };
  };
}>;

export interface MyServiceComponents {
  schemas: {
    User: {
      id: number;
      name: string;
    };
  };
}
