// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpFormData, HttpFormDataSerialized, HttpHeadersSerialized, HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema<{
  '/upload-with-literal-form-data': {
    POST: {
      request: {
        headers: HttpHeadersSerialized<{
          'content-type': 'multipart/form-data';
        }>;
        body: HttpFormData<
          HttpFormDataSerialized<{
            name: string;
            content: Blob | null;
          }>
        >;
      };
      response: {
        200: {
          headers: HttpHeadersSerialized<{
            'content-type': 'multipart/form-data';
          }>;
          body: HttpFormData<
            HttpFormDataSerialized<{
              name?: string;
              content: Blob | null;
            }>
          >;
        };
      };
    };
  };
  '/upload-with-component-form-data': {
    POST: {
      request: MyServiceComponents['requests']['formDataUpload'];
      response: {
        200: MyServiceComponents['responses']['Success'];
      };
    };
  };
}>;

export interface MyServiceComponents {
  responses: {
    Success: HttpSchema.Response<{
      headers: HttpHeadersSerialized<{
        'content-type': 'multipart/form-data';
      }>;
      body: HttpFormData<
        HttpFormDataSerialized<{
          name?: string;
          content: Blob | null;
        }>
      >;
    }>;
  };
  requests: {
    formDataUpload: HttpSchema.Request<{
      headers: HttpHeadersSerialized<{
        'content-type': 'multipart/form-data';
      }>;
      body: HttpFormData<
        HttpFormDataSerialized<{
          name: string;
          content: Blob | null;
        }>
      >;
    }>;
  };
}
