// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpHeadersSerialized, HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema<{
  '/users-with-path-item-component': MyServiceComponents['pathItems']['users'];
}>;

export interface MyServiceComponents {
  pathItems: {
    users: HttpSchema.Methods<{
      POST: {
        request: {
          headers: HttpHeadersSerialized<{
            'content-type': 'application/json';
          }>;
          body: {
            name?: string;
          };
        };
        response: {
          200: {
            headers: HttpHeadersSerialized<{
              'content-type': 'application/json';
            }>;
            body: {
              id?: string;
              name?: string;
            };
          };
        };
      };
    }>;
  };
}
