// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema<{
  '/users-with-request-body-component': {
    POST: {
      request: MyServiceComponents['requests']['requiredCreateUser'];
      response: {
        200: {};
      };
    };
  };
  '/users-with-request-body-component-having-multiple-contents': {
    POST: {
      request: MyServiceComponents['requests']['requiredCreateUserMultiple'];
      response: {
        200: {};
      };
    };
  };
  '/users-with-request-body-component-having-multiple-contents-and-parameters': {
    POST: {
      request: MyServiceComponents['requests']['requiredCreateUserMultiple'] & {
        searchParams: {
          name?: string;
        };
        headers: {
          'x-value'?: string;
        };
      };
      response: {
        200: {};
      };
    };
  };
  '/users-with-optional-request-body-component': {
    POST: {
      request: MyServiceComponents['requests']['optionalCreateUser'];
      response: {
        200: {};
      };
    };
  };
  '/users-with-optional-by-default-request-body-component': {
    POST: {
      request: MyServiceComponents['requests']['createUser'];
      response: {
        200: {};
      };
    };
  };
  '/users-with-request-body-component-and-parameters': {
    POST: {
      request: MyServiceComponents['requests']['optionalCreateUser'] & {
        searchParams: {
          name?: string;
        };
        headers: {
          'x-value'?: string;
        };
      };
      response: {
        200: {};
      };
    };
  };
  '/users-with-schema-component-in-request-body': {
    POST: {
      request: {
        headers: {
          'content-type': 'application/json';
        };
        body: MyServiceComponents['schemas']['CreateUserBody'];
      };
    };
  };
  '/users-with-schema-component-in-multiple-contents': {
    POST: {
      request:
        | {
            headers: {
              'content-type': 'application/json';
            };
            body: MyServiceComponents['schemas']['CreateUserBody'];
          }
        | {
            headers: {
              'content-type': 'application/xml';
            };
            body: MyServiceComponents['schemas']['CreateUserBody'];
          };
    };
  };
  '/users-with-schema-component-in-multiple-contents-having-parameters': {
    POST: {
      request:
        | {
            searchParams: {
              name?: string;
            };
            headers: {
              'content-type': 'application/json';
              'x-value'?: string;
            };
            body: MyServiceComponents['schemas']['CreateUserBody'];
          }
        | {
            searchParams: {
              name?: string;
            };
            headers: {
              'content-type': 'application/xml';
              'x-value'?: string;
            };
            body: MyServiceComponents['schemas']['CreateUserBody'];
          };
    };
  };
  '/users-with-optional-schema-request-body': {
    POST: {
      request: {
        headers: {
          'content-type': 'application/json';
        };
        body?: MyServiceComponents['schemas']['CreateUserBody'];
      };
    };
  };
  '/users-with-optional-by-default-schema-request-body': {
    POST: {
      request: {
        headers: {
          'content-type': 'application/json';
        };
        body?: MyServiceComponents['schemas']['CreateUserBody'];
      };
    };
  };
  '/users-with-literal-request-body': {
    POST: {
      request: {
        headers: {
          'content-type': 'application/json';
        };
        body: {
          email: string;
          password: string;
        };
      };
    };
  };
  '/users-with-literal-multiple-contents': {
    POST: {
      request:
        | {
            headers: {
              'content-type': 'application/json';
            };
            body: {
              email: string;
              password: string;
            };
          }
        | {
            headers: {
              'content-type': 'application/xml';
            };
            body: {
              name: string;
              password: string;
            };
          };
    };
  };
  '/users-with-literal-multiple-contents-having-parameters': {
    POST: {
      request:
        | {
            searchParams: {
              name?: string;
            };
            headers: {
              'content-type': 'application/json';
              'x-value'?: string;
            };
            body: {
              email: string;
              password: string;
            };
          }
        | {
            searchParams: {
              name?: string;
            };
            headers: {
              'content-type': 'application/xml';
              'x-value'?: string;
            };
            body: {
              name: string;
              password: string;
            };
          };
    };
  };
  '/users-with-optional-literal-request-body': {
    POST: {
      request: {
        headers: {
          'content-type': 'application/json';
        };
        body?: {
          email: string;
          password: string;
        };
      };
    };
  };
  '/users-with-optional-by-default-literal-request-body': {
    POST: {
      request: {
        headers: {
          'content-type': 'application/json';
        };
        body?: {
          email: string;
          password: string;
        };
      };
    };
  };
}>;

export interface MyServiceComponents {
  schemas: {
    CreateUserBody: {
      name?: string;
      email: string;
      password: string;
    };
  };
  requests: {
    createUser: {
      headers: {
        'content-type': 'application/json';
      };
      body?: {
        name?: string;
        email: string;
        password: string;
      };
    };
    requiredCreateUser: {
      headers: {
        'content-type': 'application/json';
      };
      body: {
        name?: string;
        email: string;
        password: string;
      };
    };
    requiredCreateUserMultiple:
      | {
          headers: {
            'content-type': 'application/json';
          };
          body: {
            email: string;
            password: string;
          };
        }
      | {
          headers: {
            'content-type': 'application/xml';
          };
          body: {
            name: string;
            password: string;
          };
        };
    optionalCreateUser: {
      headers: {
        'content-type': 'application/json';
      };
      body?: {
        name?: string;
        email: string;
        password: string;
      };
    };
  };
}
