// Auto-generated by zimic.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpHeadersSerialized, HttpSchema, HttpStatusCode, MergeHttpResponsesByStatusCode } from '@/index';

export type MyServiceSchema = HttpSchema<{
  '/users-with-non-numeric-status-codes': {
    POST: {
      response: MergeHttpResponsesByStatusCode<
        [
          {
            /** Continue */
            100: {};
            201: MyServiceComponents['responses']['userCreated'];
            400: MyServiceComponents['responses']['validationError'];
            404: MyServiceComponents['responses']['notFoundError'];
            /** Service Unavailable */
            503: {};
          },
          {
            /** Informational */
            [StatusCode in HttpStatusCode.Information]: {};
          },
          {
            /** Success */
            [StatusCode in HttpStatusCode.Success]: {};
          },
          {
            [StatusCode in HttpStatusCode.ClientError]: MyServiceComponents['responses']['clientError'];
          },
          {
            [StatusCode in HttpStatusCode.ServerError]: MyServiceComponents['responses']['serverError'];
          },
          {
            [StatusCode in HttpStatusCode]: MyServiceComponents['responses']['error'];
          },
        ]
      >;
    };
  };
  '/users-with-no-request': {
    POST: {
      response: MergeHttpResponsesByStatusCode<
        [
          {
            200: MyServiceComponents['responses']['userCreated'];
          },
          {
            [StatusCode in HttpStatusCode]: MyServiceComponents['responses']['error'];
          },
        ]
      >;
    };
  };
  '/users-with-multiple-reference-response-contents': {
    POST: {
      response: {
        200: MyServiceComponents['responses']['userCreatedMultipleContents'];
        400: MyServiceComponents['responses']['error'];
      };
    };
  };
  '/users-with-multiple-literal-response-contents': {
    POST: {
      response: {
        /** Success */
        200:
          | {
              headers: HttpHeadersSerialized<{
                'content-type': 'application/json';
              }>;
              body: {
                /**
                 * The type of the response
                 *
                 * @enum {string}
                 */
                type: 'user-as-json';
                value: MyServiceComponents['schemas']['User'];
              };
            }
          | {
              headers: HttpHeadersSerialized<{
                'content-type': 'application/xml';
              }>;
              body: {
                /**
                 * The type of the response
                 *
                 * @enum {string}
                 */
                type: 'user-as-xml';
                value: MyServiceComponents['schemas']['User'];
              };
            };
        400: MyServiceComponents['responses']['error'];
      };
    };
  };
  '/users-with-multiple-literal-response-contents-having-headers': {
    POST: {
      response: {
        /** Success */
        200:
          | {
              headers: HttpHeadersSerialized<{
                'content-type': 'application/json';
                'x-value'?: string;
              }>;
              body: {
                /**
                 * The type of the response
                 *
                 * @enum {string}
                 */
                type: 'user-as-json';
                value: MyServiceComponents['schemas']['User'];
              };
            }
          | {
              headers: HttpHeadersSerialized<{
                'content-type': 'application/xml';
                'x-value'?: string;
              }>;
              body: {
                /**
                 * The type of the response
                 *
                 * @enum {string}
                 */
                type: 'user-as-xml';
                value: MyServiceComponents['schemas']['User'];
              };
            };
        400: MyServiceComponents['responses']['error'];
      };
    };
  };
  '/users-with-no-response-content': {
    POST: {
      response: {
        /** Success */
        200: {};
      };
    };
  };
  '/users-with-no-request-or-response': {
    /** Empty */
    POST: {};
  };
}>;

export interface MyServiceComponents {
  schemas: {
    /** A user */
    User: {
      /** The user ID */
      id: string;
      /** The user's name */
      name?: string;
      /** The user's email address */
      email: string;
      /** The date and time the user was created */
      createdAt: string;
      /** The date and time the user was last updated */
      updatedAt: string;
    };
  };
  responses: {
    /** Success */
    userCreated: HttpSchema.Response<{
      headers: HttpHeadersSerialized<{
        'content-type': 'application/json';
      }>;
      body: MyServiceComponents['schemas']['User'];
    }>;
    /** Success */
    userCreatedMultipleContents: HttpSchema.Response<
      | {
          headers: HttpHeadersSerialized<{
            'content-type': 'application/json';
          }>;
          body: {
            /**
             * The type of the response
             *
             * @enum {string}
             */
            type?: 'user-as-json';
            value?: MyServiceComponents['schemas']['User'];
          };
        }
      | {
          headers: HttpHeadersSerialized<{
            'content-type': 'application/xml';
          }>;
          body: {
            /**
             * The type of the response
             *
             * @enum {string}
             */
            type?: 'user-as-xml';
            value?: MyServiceComponents['schemas']['User'];
          };
        }
    >;
    /** Not Found */
    notFoundError: HttpSchema.Response<{
      headers: HttpHeadersSerialized<{
        'content-type': 'application/json';
      }>;
      body: {
        /** A message describing the error */
        message: string;
        /** @enum {string} */
        code?: 'NOT_FOUND';
      };
    }>;
    /** Validation Error */
    validationError: HttpSchema.Response<{
      headers: HttpHeadersSerialized<{
        'content-type': 'application/json';
      }>;
      body: {
        /** A message describing the error */
        message: string;
        /** @enum {string} */
        code?: 'VALIDATION_ERROR';
      };
    }>;
    /** Client Error */
    clientError: HttpSchema.Response<{
      headers: HttpHeadersSerialized<{
        'content-type': 'application/json';
      }>;
      body: {
        /** A message describing the error */
        message: string;
        /** @enum {string} */
        code?: 'CLIENT_ERROR';
      };
    }>;
    /** Server Error */
    serverError: HttpSchema.Response<{
      headers: HttpHeadersSerialized<{
        'content-type': 'application/json';
      }>;
      body: {
        /** A message describing the error */
        message: string;
        /** @enum {string} */
        code?: 'SERVER_ERROR';
      };
    }>;
    /** Error */
    error: HttpSchema.Response<{
      headers: HttpHeadersSerialized<{
        'content-type': 'application/json';
      }>;
      body: {
        /** A message describing the error */
        message: string;
      };
    }>;
  };
}
