// Auto-generated by @zimic/http.
// NOTE: Do not manually edit this file. Changes will be overridden.

import type { HttpSchema } from '@/index';

export type MyServiceSchema = HttpSchema<{
  '/users': {
    /** List users */
    GET: MyServiceOperations['users/list'];
    /** Create user */
    POST: MyServiceOperations['users/create'];
  };
}>;

export interface MyServiceComponents {
  schemas: {
    User: {
      /**
       * The user's id
       *
       * @example
       *   be8253f9-124b-4c32-b046-c25b6fd0af0c
       */
      id: string;
      /**
       * The user's name
       *
       * @example
       *   John;
       */
      name?: string;
      /**
       * The user's email
       *
       * @example
       *   john@email.com
       */
      email: string;
      /**
       * The user's creation date
       *
       * @example
       *   2024-01-01T00:00:00.000Z
       */
      createdAt: string;
      /**
       * The user's last update date
       *
       * @example
       *   2024-01-01T00:00:00.000Z
       */
      updatedAt: string;
    };
  };
}

export interface MyServiceOperations {
  'users/list': {
    request: {
      searchParams: {
        /** How many items to return */
        limit: number;
        /** The UTM source */
        utm_source?: string;
      };
      headers: {
        /** The authorization token */
        authorization: string;
      };
    };
    response: {
      /** Success */
      200: {
        headers: {
          'content-type': 'application/json';
        };
        body: MyServiceComponents['schemas']['User'][];
      };
      /** Error */
      400: {
        headers: {
          'content-type': 'application/json';
        };
        body: {
          message: string;
        };
      };
    };
  };
  'users/create': {
    /** The user to create */
    request: {
      searchParams: {
        /** The UTM source */
        utm_source?: string;
      };
      headers: {
        'content-type': 'application/json';
        /** The authorization token */
        authorization: string;
      };
      body: {
        /**
         * The user's name
         *
         * @example
         *   John;
         */
        name?: string;
        /**
         * The user's email
         *
         * @example
         *   john@email.com
         */
        email: string;
        /**
         * The user's password
         *
         * @example
         *   123456;
         */
        password: string;
      };
    };
    response: {
      /** The user was created successfully */
      200: {
        headers: {
          'content-type': 'application/json';
        };
        body: MyServiceComponents['schemas']['User'];
      };
      /** Error */
      400: {
        headers: {
          'content-type': 'application/json';
        };
        body: {
          /** The error message */
          message: string;
        };
      };
    };
  };
}
