import path from 'path';

import { TypegenFixtureCase } from './types';

const openapiTypegenFixtureCases = {
  get all() {
    return Object.keys(this)
      .filter((key) => key !== 'all')
      .sort()
      .flatMap((key) => this[key]);
  },

  simple: [
    {
      inputFileName: 'simple.yaml',
      expectedOutputFileName: 'simple.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'simple.yaml',
      expectedOutputFileName: 'simple.comments.ts',
      additionalArguments: [],
    },
    {
      inputFileName: 'simple.yaml',
      expectedOutputFileName: 'simple.ts',
      additionalArguments: ['--no-comments'],
      shouldWriteToStdout: true,
    },
  ],

  pathParams: [
    {
      inputFileName: 'pathParams.yaml',
      expectedOutputFileName: 'pathParams.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'pathParams.yaml',
      expectedOutputFileName: 'pathParams.comments.ts',
      additionalArguments: [],
    },
  ],

  searchParams: [
    {
      inputFileName: 'searchParams.yaml',
      expectedOutputFileName: 'searchParams.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'searchParams.yaml',
      expectedOutputFileName: 'searchParams.comments.ts',
      additionalArguments: [],
    },
  ],

  headers: [
    {
      inputFileName: 'headers.yaml',
      expectedOutputFileName: 'headers.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'headers.yaml',
      expectedOutputFileName: 'headers.comments.ts',
      additionalArguments: [],
    },
  ],

  requestBodies: [
    {
      inputFileName: 'requestBodies.yaml',
      expectedOutputFileName: 'requestBodies.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'requestBodies.yaml',
      expectedOutputFileName: 'requestBodies.comments.ts',
      additionalArguments: [],
    },
  ],

  responses: [
    {
      inputFileName: 'responses.yaml',
      expectedOutputFileName: 'responses.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'responses.yaml',
      expectedOutputFileName: 'responses.comments.ts',
      additionalArguments: [],
    },
  ],

  formData: [
    {
      inputFileName: 'formData.yaml',
      expectedOutputFileName: 'formData.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'formData.yaml',
      expectedOutputFileName: 'formData.comments.ts',
      additionalArguments: [],
    },
  ],

  binary: [
    {
      inputFileName: 'binary.yaml',
      expectedOutputFileName: 'binary.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'binary.yaml',
      expectedOutputFileName: 'binary.comments.ts',
      additionalArguments: [],
    },
  ],

  // Not pruning unused operations and components because path items are not being generated by openapi-typescript.
  // See https://github.com/openapi-ts/openapi-typescript/issues/1725
  pathItems: [
    {
      inputFileName: 'pathItems.yaml',
      expectedOutputFileName: 'pathItems.ts',
      additionalArguments: ['--no-comments', '--no-prune'],
    },
    {
      inputFileName: 'pathItems.yaml',
      expectedOutputFileName: 'pathItems.comments.ts',
      additionalArguments: ['--no-prune'],
    },
  ],

  combinations: [
    {
      inputFileName: 'combinations.yaml',
      expectedOutputFileName: 'combinations.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'combinations.yaml',
      expectedOutputFileName: 'combinations.comments.ts',
      additionalArguments: [],
    },
  ],

  examples: [
    {
      inputFileName: 'examples.yaml',
      expectedOutputFileName: 'examples.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'examples.yaml',
      expectedOutputFileName: 'examples.comments.ts',
      additionalArguments: [],
    },
  ],

  security: [
    {
      inputFileName: 'security.yaml',
      expectedOutputFileName: 'security.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'security.yaml',
      expectedOutputFileName: 'security.comments.ts',
      additionalArguments: [],
    },
  ],

  filters: [
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.comments.ts',
      additionalArguments: [],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.oneMethod.ts',
      additionalArguments: ['--no-comments', '--filter', 'GET /users'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.multipleMethods.ts',
      additionalArguments: ['--no-comments', '--filter', 'GET,PUT /users/:userId'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.wildcardMethod.ts',
      additionalArguments: ['--no-comments', '--filter', '* /users/:userId'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.pathWildcard.1.ts',
      additionalArguments: ['--no-comments', '--filter', 'GET *'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.pathWildcard.2.ts',
      additionalArguments: ['--no-comments', '--filter', 'GET **'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.pathWildcard.3.ts',
      additionalArguments: ['--no-comments', '--filter', 'GET /users**'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.pathWildcard.4.ts',
      additionalArguments: ['--no-comments', '--filter', 'GET /users/**'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.pathWildcard.5.ts',
      additionalArguments: ['--no-comments', '--filter', 'GET /users/**/*'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.negative.1.ts',
      additionalArguments: ['--no-comments', '--filter', '!GET /users'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.negative.2.ts',
      additionalArguments: ['--no-comments', '--filter', '!* /users**'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.negative.3.ts',
      additionalArguments: ['--no-comments', '--filter', '!GET /users/**/*'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.empty.ts',
      additionalArguments: ['--no-comments', '--filter', '!* **'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.multiple.ts',
      additionalArguments: [
        '--no-comments',
        '--filter',
        'POST /*',
        '--filter',
        '* /users/**/*',
        '--filter',
        '!PATCH /users/:userId',
        '--filter',
        'DELETE /notifications',
      ],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.multipleFromFile.ts',
      additionalArguments: ['--no-comments', '--filter-file', path.join(__dirname, 'openapi', 'filters.txt')],
    },

    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.oneMethod.notPruned.ts',
      additionalArguments: ['--no-comments', '--no-prune', '--filter', 'GET /users'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.wildcardMethod.notPruned.ts',
      additionalArguments: ['--no-comments', '--no-prune', '--filter', '* /users/:userId'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.empty.notPruned.ts',
      additionalArguments: ['--no-comments', '--no-prune', '--filter', '!* **'],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.multiple.notPruned.ts',
      additionalArguments: [
        '--no-comments',
        '--no-prune',
        '--filter',
        'POST /users',
        '--filter',
        '* /users/**/*',
        '--filter',
        '!PATCH /users/:userId',
        '--filter',
        'DELETE /notifications',
      ],
    },
    {
      inputFileName: 'filters.yaml',
      expectedOutputFileName: 'filters.multipleFromFile.notPruned.ts',
      additionalArguments: [
        '--no-comments',
        '--no-prune',
        '--filter-file',
        path.join(__dirname, 'openapi', 'filters.txt'),
      ],
    },
  ],

  empty: [
    {
      inputFileName: 'empty.yaml',
      expectedOutputFileName: 'empty.ts',
      additionalArguments: ['--no-comments'],
    },
    {
      inputFileName: 'empty.yaml',
      expectedOutputFileName: 'empty.comments.ts',
      additionalArguments: [],
    },
  ],
} satisfies Record<string, TypegenFixtureCase[]>;

export default openapiTypegenFixtureCases;
