import { GitHubRepository } from '../../../src/clients/github/types';
import githubInterceptor from './interceptor';

export const githubMockData = {
  repositories: [
    {
      id: 1,
      name: 'zimic-example',
      node_id: 'R_kgDOKwY08A',
      full_name: 'zimicjs/zimic-example',
      private: false,
      html_url: 'https://github.com/zimicjs/zimic-example',
      owner: {
        login: 'zimicjs',
        id: 161985413,
        node_id: 'O_kgDOCaezhQ',
        avatar_url: 'https://avatars.githubusercontent.com/u/161985413?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/zimicjs',
        html_url: 'https://github.com/zimicjs',
        followers_url: 'https://api.github.com/users/zimicjs/followers',
        following_url: 'https://api.github.com/users/zimicjs/following{/other_user}',
        gists_url: 'https://api.github.com/users/zimicjs/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/zimicjs/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/zimicjs/subscriptions',
        organizations_url: 'https://api.github.com/users/zimicjs/orgs',
        repos_url: 'https://api.github.com/users/zimicjs/repos',
        events_url: 'https://api.github.com/users/zimicjs/events{/privacy}',
        received_events_url: 'https://api.github.com/users/zimicjs/received_events',
        type: 'Organization',
        user_view_type: 'public',
        site_admin: false,
      },
      description: 'Next-gen, TypeScript-first HTTP integrations',
      fork: false,
      url: 'https://api.github.com/repos/zimicjs/zimic',
      forks_url: 'https://api.github.com/repos/zimicjs/zimic/forks',
      keys_url: 'https://api.github.com/repos/zimicjs/zimic/keys{/key_id}',
      collaborators_url: 'https://api.github.com/repos/zimicjs/zimic/collaborators{/collaborator}',
      teams_url: 'https://api.github.com/repos/zimicjs/zimic/teams',
      hooks_url: 'https://api.github.com/repos/zimicjs/zimic/hooks',
      issue_events_url: 'https://api.github.com/repos/zimicjs/zimic/issues/events{/number}',
      events_url: 'https://api.github.com/repos/zimicjs/zimic/events',
      assignees_url: 'https://api.github.com/repos/zimicjs/zimic/assignees{/user}',
      branches_url: 'https://api.github.com/repos/zimicjs/zimic/branches{/branch}',
      tags_url: 'https://api.github.com/repos/zimicjs/zimic/tags',
      blobs_url: 'https://api.github.com/repos/zimicjs/zimic/git/blobs{/sha}',
      git_tags_url: 'https://api.github.com/repos/zimicjs/zimic/git/tags{/sha}',
      git_refs_url: 'https://api.github.com/repos/zimicjs/zimic/git/refs{/sha}',
      trees_url: 'https://api.github.com/repos/zimicjs/zimic/git/trees{/sha}',
      statuses_url: 'https://api.github.com/repos/zimicjs/zimic/statuses/{sha}',
      languages_url: 'https://api.github.com/repos/zimicjs/zimic/languages',
      stargazers_url: 'https://api.github.com/repos/zimicjs/zimic/stargazers',
      contributors_url: 'https://api.github.com/repos/zimicjs/zimic/contributors',
      subscribers_url: 'https://api.github.com/repos/zimicjs/zimic/subscribers',
      subscription_url: 'https://api.github.com/repos/zimicjs/zimic/subscription',
      commits_url: 'https://api.github.com/repos/zimicjs/zimic/commits{/sha}',
      git_commits_url: 'https://api.github.com/repos/zimicjs/zimic/git/commits{/sha}',
      comments_url: 'https://api.github.com/repos/zimicjs/zimic/comments{/number}',
      issue_comment_url: 'https://api.github.com/repos/zimicjs/zimic/issues/comments{/number}',
      contents_url: 'https://api.github.com/repos/zimicjs/zimic/contents/{+path}',
      compare_url: 'https://api.github.com/repos/zimicjs/zimic/compare/{base}...{head}',
      merges_url: 'https://api.github.com/repos/zimicjs/zimic/merges',
      archive_url: 'https://api.github.com/repos/zimicjs/zimic/{archive_format}{/ref}',
      downloads_url: 'https://api.github.com/repos/zimicjs/zimic/downloads',
      issues_url: 'https://api.github.com/repos/zimicjs/zimic/issues{/number}',
      pulls_url: 'https://api.github.com/repos/zimicjs/zimic/pulls{/number}',
      milestones_url: 'https://api.github.com/repos/zimicjs/zimic/milestones{/number}',
      notifications_url: 'https://api.github.com/repos/zimicjs/zimic/notifications{?since,all,participating}',
      labels_url: 'https://api.github.com/repos/zimicjs/zimic/labels{/name}',
      releases_url: 'https://api.github.com/repos/zimicjs/zimic/releases{/id}',
      deployments_url: 'https://api.github.com/repos/zimicjs/zimic/deployments',
      created_at: '2023-11-21T21:14:37Z',
      updated_at: '2025-04-16T00:56:59Z',
      pushed_at: '2025-04-15T23:40:42Z',
      git_url: 'git://github.com/zimicjs/zimic.git',
      ssh_url: 'git@github.com:zimicjs/zimic.git',
      clone_url: 'https://github.com/zimicjs/zimic.git',
      svn_url: 'https://github.com/zimicjs/zimic',
      homepage: 'https://github.com/zimicjs/zimic',
      size: 4377,
      stargazers_count: 16,
      watchers_count: 16,
      language: 'TypeScript',
      has_issues: true,
      has_projects: true,
      has_downloads: true,
      has_wiki: true,
      has_pages: false,
      has_discussions: true,
      forks_count: 3,
      mirror_url: null,
      archived: false,
      disabled: false,
      open_issues_count: 26,
      license: {
        key: 'mit',
        name: 'MIT License',
        spdx_id: 'MIT',
        url: 'https://api.github.com/licenses/mit',
        node_id: 'MDc6TGljZW5zZTEz',
      },
      allow_forking: true,
      is_template: false,
      web_commit_signoff_required: false,
      topics: [
        'api',
        'fetch',
        'http',
        'mock',
        'msw',
        'openapi',
        'service-workers',
        'tests',
        'typegen',
        'types',
        'typescript',
      ],
      visibility: 'public',
      forks: 3,
      open_issues: 26,
      watchers: 16,
      default_branch: 'canary',
      temp_clone_token: null,
      custom_properties: {},
      organization: {
        login: 'zimicjs',
        id: 161985413,
        node_id: 'O_kgDOCaezhQ',
        avatar_url: 'https://avatars.githubusercontent.com/u/161985413?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/zimicjs',
        html_url: 'https://github.com/zimicjs',
        followers_url: 'https://api.github.com/users/zimicjs/followers',
        following_url: 'https://api.github.com/users/zimicjs/following{/other_user}',
        gists_url: 'https://api.github.com/users/zimicjs/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/zimicjs/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/zimicjs/subscriptions',
        organizations_url: 'https://api.github.com/users/zimicjs/orgs',
        repos_url: 'https://api.github.com/users/zimicjs/repos',
        events_url: 'https://api.github.com/users/zimicjs/events{/privacy}',
        received_events_url: 'https://api.github.com/users/zimicjs/received_events',
        type: 'Organization',
        user_view_type: 'public',
        site_admin: false,
      },
      network_count: 3,
      subscribers_count: 2,
      anonymous_access_enabled: false,
    },
  ] satisfies GitHubRepository[],

  apply() {
    githubInterceptor.get('/repos/:owner/:name').respond({
      status: 404,
      body: { message: 'Not Found' },
    });

    for (const repository of this.repositories) {
      githubInterceptor
        .get(`/repos/${repository.owner.login}/${repository.name}`)
        .respond({ status: 200, body: repository });
    }
  },
};
