import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebarsConfig: SidebarsConfig = {
  zimic: [{ type: 'autogenerated', dirName: 'zimic' }],
  'zimic-http': [{ type: 'autogenerated', dirName: 'zimic-http' }],
  'zimic-fetch': [{ type: 'autogenerated', dirName: 'zimic-fetch' }],
  'zimic-interceptor': [{ type: 'autogenerated', dirName: 'zimic-interceptor' }],
};

export default sidebarsConfig;
