import filesystem from 'fs/promises';
import generateTypesFromOpenAPI, { SchemaObject, astToString as convertTypeASTToString } from 'openapi-typescript';
import path from 'path';
import ts from 'typescript';

import { version } from '@@/package.json';

import { createFileURL } from '@/utils/urls';

import { createBlobType, createNullType, createUnionType } from '../utils/types';

function transformSchemaObject(schemaObject: SchemaObject) {
  if (schemaObject.format === 'binary') {
    const blobType = createBlobType();

    if (schemaObject.nullable) {
      const nullType = createNullType();
      return createUnionType([blobType, nullType]);
    }

    return blobType;
  }
}

export async function importTypesFromOpenAPI(filePath: string) {
  const fileURL = createFileURL(path.resolve(filePath));

  const rawNodes = await generateTypesFromOpenAPI(fileURL, {
    alphabetize: false,
    additionalProperties: false,
    excludeDeprecated: false,
    propertiesRequiredByDefault: false,
    defaultNonNullable: true,
    pathParamsAsTypes: false,
    emptyObjectsUnknown: true,
    exportType: false,
    arrayLength: false,
    immutable: false,
    enumValues: false,
    enum: false,
    silent: true,
    transform: transformSchemaObject,
  });

  return rawNodes;
}

export function convertTypesToString(nodes: ts.Node[], options: { removeComments: boolean }) {
  const typeOutput = convertTypeASTToString(nodes, {
    formatOptions: options,
  });

  return typeOutput;
}

function prepareTypeOutputToSave(output: string) {
  const formattedOutput = output
    .replace(/^export (\w+)/gm, '\nexport $1')
    .replace(/^( {4})+/gm, (match) => match.replace(/ {4}/g, '  '));

  const formattedOutputWithPrefix = [
    `// Auto-generated by zimic@${version}.`,
    '// Note! Changes to this file will be overwritten.\n',
    formattedOutput,
  ].join('\n');

  return formattedOutputWithPrefix;
}

async function writeTypeOutputToFile(outputFilePath: string, formattedOutput: string) {
  await filesystem.writeFile(path.resolve(outputFilePath), formattedOutput);
}

async function writeTypeOutputToStandardOutput(formattedOutput: string) {
  await new Promise((resolve) => {
    process.stdout.write(formattedOutput, 'utf-8', resolve);
  });
}

export async function writeTypeOutput(typeOutput: string, outputFilePath: string) {
  const formattedOutput = prepareTypeOutputToSave(typeOutput);

  const isFileOutput = outputFilePath !== '-';
  if (isFileOutput) {
    await writeTypeOutputToFile(outputFilePath, formattedOutput);
  } else {
    await writeTypeOutputToStandardOutput(formattedOutput);
  }
}
