import clsx from 'clsx';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PropsWithChildren } from 'react';

import { loadInterceptors } from '../../tests/interceptors';
import InterceptorProvider from '../providers/interceptors/InterceptorProvider';

import '../styles/global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Search a GitHub repository',
  description: 'Generated by create-next-app',
};

async function RootLayout({ children }: PropsWithChildren) {
  await loadInterceptors();

  return (
    <html lang="en">
      <body className={clsx(inter.className, 'bg-slate-100 flex flex-col items-center justify-center min-h-screen')}>
        <InterceptorProvider>{children}</InterceptorProvider>
      </body>
    </html>
  );
}

export default RootLayout;
