name: Release Wiki

on:
  release:
    types:
      - published

concurrency:
  group: release-wiki
  cancel-in-progress: false

env:
  NODE_VERSION: 20
  TURBO_LOG_ORDER: stream

jobs:
  release-zimic-wiki:
    name: Release zimic to NPM
    runs-on: ubuntu-latest
    timeout-minutes: 15

    environment: Wiki

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get zimic release version
        id: zimic-version
        uses: ./.github/actions/zimic-version
        with:
          ref-name: ${{ github.ref_name }}

      - name: Checkout wiki
        uses: actions/checkout@v4
        # if: ${{ steps.zimic-version.outputs.label == 'latest' }}
        with:
          repository: zimicjs/zimic.wiki

      - name: Sync wiki with markdown docs
        # if: ${{ steps.zimic-version.outputs.label == 'latest' }}
        working-directory: zimic.wiki
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'

          rsync --archive --verbose --delete ../../docs/wiki/ .

          # Point "../../examples*" links to the current ref on  GitHub
          sed -E -i "s/\\]\\(\\.\\.\\/\\.\\.\\/examples([^\\)]+)\\)/](https:\\/\\/github.com\\/zimicjs\\/zimic\\/tree\\/${{ github.ref_name }}\\/examples\\1)/g" *.md

          # Copy all images to the wiki
          find ../docs -type f -name '*.png' -exec cp {} . \;
          sed -E -i "s/\\]\\(.+\\/([^.]+)\\.png/](.\\/\\1.png/g" *.md

          git add .
          git commit -m "docs(wiki): zimic@${{ steps.zimic-version.outputs.value }}"
          git push
