name: Release to GitHub

on:
  push:
    branches:
      - main
    tags:
      - v*.*.*-canary.*
      - '!v*.*.*-zimic'

concurrency:
  group: release-github-${{ github.ref_name }}
  cancel-in-progress: true

env:
  TURBO_TOKEN: ${{ secrets.TURBO_REMOTE_CACHE_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_REMOTE_CACHE_TEAM }}
  TURBO_LOG_ORDER: stream

jobs:
  release-to-github:
    name: Release to GitHub
    runs-on: ubuntu-latest
    timeout-minutes: 3

    environment: GitHub

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get zimic release version
        id: zimic-version
        run: |
          version=$(jq -r '.version' ./packages/zimic/package.json)
          echo "value=$version" >> $GITHUB_OUTPUT

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          name: v${{ steps.zimic-version.outputs.value }}
          tag: v${{ steps.zimic-version.outputs.value }}
          commit: ${{ github.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
          makeLatest: ${{ startsWith(github.ref, 'refs/heads/') && github.ref_name == 'main' }}
          prerelease: ${{ !(startsWith(github.ref, 'refs/heads/') && github.ref_name == 'main') }}
          allowUpdates: ${{ !(startsWith(github.ref, 'refs/heads/') && github.ref_name == 'main') }}
          replacesArtifacts: ${{ !(startsWith(github.ref, 'refs/heads/') && github.ref_name == 'main') }}
          generateReleaseNotes: true
          draft: true
