name: 'Release Package: @zimic/http'

on:
  release:
    types:
      - published
  push:
    tags:
      - '@zimic/http@*-*'

concurrency:
  group: release-zimic-http-${{ github.ref_name }}
  cancel-in-progress: false

env:
  TURBO_TOKEN: ${{ secrets.TURBO_REMOTE_CACHE_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_REMOTE_CACHE_TEAM }}
  TURBO_LOG_ORDER: stream

jobs:
  release-to-npm:
    name: Release to NPM
    runs-on: blacksmith-2vcpu-ubuntu-2404
    if: ${{ startsWith(github.ref_name, '@zimic/http@') }}
    timeout-minutes: 7

    environment: NPM

    permissions:
      contents: read
      id-token: write

    outputs:
      version-value: ${{ steps.release.outputs.version-value }}
      version-label: ${{ steps.release.outputs.version-label }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Release to NPM
        id: release
        uses: ./.github/actions/zimic-release-npm
        with:
          ref-name: ${{ github.ref_name }}
          project-name: '@zimic/http'
          project-directory: packages/zimic-http

  test-npm-release:
    name: Test NPM release
    runs-on: blacksmith-2vcpu-ubuntu-2404
    timeout-minutes: 15

    needs:
      - release-to-npm

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          ref: canary

      - name: Test NPM release
        uses: ./.github/actions/zimic-release-npm-test
        with:
          ref-name: ${{ github.ref_name }}
          project-name: '@zimic/http'
          project-directory: packages/zimic-http
          turbo-token: ${{ env.TURBO_TOKEN }}
          turbo-team: ${{ env.TURBO_TEAM }}

  publish-release-comments:
    name: Publish release comments
    runs-on: blacksmith-2vcpu-ubuntu-2404
    timeout-minutes: 15
    if: ${{ needs.release-to-npm.outputs.version-label == 'latest' }}

    needs:
      - release-to-npm

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Publish release comments
        uses: ./.github/actions/zimic-release-comments
        with:
          type: package
          ref-name: ${{ github.ref_name }}
          project-name: '@zimic/http'
