name: Release Comments

on:
  workflow_dispatch:
    inputs:
      project-name:
        description: The project name to create release comments for
        required: true

concurrency:
  group: release-comments-${{ github.ref_name }}
  cancel-in-progress: false

jobs:
  publish-release-comments:
    name: Publish release comments
    runs-on: ubuntu-latest
    timeout-minutes: 15

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Publish release comments
        uses: ./.github/actions/zimic-release-comments
        with:
          ref-name: ${{ github.ref_name }}
          project-name: ${{ inputs.project-name }}
