name: 'Release to Vercel: zimic-web'

on:
  push:
    tags:
      - 'zimic-web@*'

concurrency:
  group: release-zimic-web-to-vercel
  cancel-in-progress: false

env:
  TURBO_TOKEN: ${{ secrets.TURBO_REMOTE_CACHE_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_REMOTE_CACHE_TEAM }}
  TURBO_LOG_ORDER: stream

jobs:
  release-zimic-web-to-vercel:
    name: Release zimic-web to vercel
    runs-on: ubuntu-latest
    timeout-minutes: 4

    environment: Vercel

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Release zimic-web
        uses: ./.github/actions/zimic-web-release
        with:
          vercel-repository: ${{ secrets.ZIMIC_WEB_VERCEL_REPOSITORY }}
          vercel-ssh-key: ${{ secrets.ZIMIC_WEB_VERCEL_SSH_KEY }}
          vercel-branch: ${{ contains(github.ref_name, '-') &&  'vercel-canary' || 'vercel-main' }}
