name: Release Wiki

on:
  release:
    types:
      - published

concurrency:
  group: release-wiki
  cancel-in-progress: false

env:
  NODE_VERSION: 20
  TURBO_LOG_ORDER: stream

jobs:
  release-zimic-wiki:
    name: Release zimic to NPM
    runs-on: ubuntu-latest
    timeout-minutes: 5

    environment: Wiki

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: zimic

      - name: Get zimic release version
        id: zimic-version
        uses: ./.github/actions/zimic-version
        with:
          ref-name: ${{ github.ref_name }}
          working-directory: zimic

      - name: Checkout wiki
        uses: actions/checkout@v4
        # if: ${{ steps.zimic-version.outputs.label == 'latest' }}
        with:
          repository: zimicjs/zimic.wiki
          path: zimic.wiki

      - name: Sync wiki with markdown docs
        # if: ${{ steps.zimic-version.outputs.label == 'latest' }}
        working-directory: zimic.wiki
        run: |
          git config user.name '${{ vars.ZIMIC_WIKI_COMMIT_USER_NAME }}'
          git config user.email '${{ vars.ZIMIC_WIKI_COMMIT_USER_EMAIL }}'

          bash scripts/sync.sh '${{ github.ref_name }}'

          git add .
          git commit -m 'docs(wiki): zimic@${{ steps.zimic-version.outputs.value }}'
          git push
