name: Release zimic-http Package

on:
  release:
    types:
      - published

concurrency:
  group: release-zimic-http-${{ github.ref_name }}
  cancel-in-progress: false

env:
  TURBO_LOG_ORDER: stream

jobs:
  release-to-npm:
    name: Release to NPM
    runs-on: ubuntu-latest
    timeout-minutes: 7

    environment: NPM

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Release to NPM
        uses: ./zimic/.github/actions/zimic-release-npm
        with:
          ref-name: ${{ github.ref_name }}
          project-name: '@zimic/http'
          project-directory: packages/zimic-http
          npm-token: ${{ secrets.ZIMIC_NPM_RELEASE_TOKEN }}

  test-npm-release:
    name: Test NPM release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - release-to-npm

    steps:
      - name: Test NPM release
        uses: ./zimic/.github/actions/zimic-release-npm-test
        with:
          ref-name: ${{ github.ref_name }}
          project-name: '@zimic/http'
          project-directory: packages/zimic-http

  release-docs:
    name: Release documentation
    runs-on: ubuntu-latest
    timeout-minutes: 5

    environment: Wiki

    permissions:
      contents: write

    steps:
      - name: Release documentation
        uses: ./zimic/.github/actions/zimic-release-docs
        with:
          ref-name: ${{ github.ref_name }}
          project-name: '@zimic/http'
          project-directory: packages/zimic-http
          wiki-ssh-key: ${{ secrets.RELEASE_GITHUB_PUSH_KEY }}

  publish-release-comments:
    name: Publish release comments
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - release-to-npm
      - test-npm-release
      - release-docs

    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Publish release comments
        uses: ./zimic/.github/actions/zimic-release-comments
        with:
          ref-name: ${{ github.ref_name }}
          project-name: '@zimic/http'
